version: 2
jobs:
  build-deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build and push images
          command: |
            docker login --username $DOCKER_LOGIN --password $DOCKER_PASSWORD
            bash build-push.sh
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-deploy:
          filters:
            branches:
              only: master
